# Generated by Django 4.2 on 2024-03-26 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApexTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('meta_content', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeployJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata_type', models.CharField(blank=True, max_length=255, null=True)),
                ('deploy_result', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('error', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('finished_date', models.DateTimeField(blank=True, null=True)),
                ('org_id', models.CharField(max_length=255)),
                ('org_name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('instance_url', models.CharField(blank=True, max_length=255, null=True)),
                ('json_message', models.TextField(blank=True, null=True)),
                ('is_sandbox', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('error', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField()),
                ('actions', models.TextField(blank=True, null=True)),
                ('booleanFilter', models.CharField(blank=True, max_length=255, null=True)),
                ('criteriaItems', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('formula', models.TextField(blank=True, null=True)),
                ('fullName', models.CharField(blank=True, max_length=255, null=True)),
                ('triggerType', models.CharField(blank=True, max_length=255, null=True)),
                ('workflowTimeTriggers', models.TextField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enable_disable.job')),
            ],
        ),
        migrations.CreateModel(
            name='ValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField()),
                ('description', models.TextField(blank=True, null=True)),
                ('errorConditionFormula', models.TextField(blank=True, null=True)),
                ('errorDisplayField', models.CharField(blank=True, max_length=255, null=True)),
                ('errorMessage', models.TextField(blank=True, null=True)),
                ('fullName', models.CharField(blank=True, max_length=255, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enable_disable.job')),
            ],
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_id', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('latest_version', models.SmallIntegerField(blank=True, null=True)),
                ('active_version', models.SmallIntegerField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enable_disable.job')),
            ],
        ),
        migrations.CreateModel(
            name='DeployJobComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField()),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('deploy_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enable_disable.deployjob')),
                ('flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enable_disable.flow')),
                ('trigger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enable_disable.apextrigger')),
                ('validation_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enable_disable.validationrule')),
                ('workflow_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enable_disable.workflowrule')),
            ],
        ),
        migrations.AddField(
            model_name='deployjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enable_disable.job'),
        ),
        migrations.AddField(
            model_name='apextrigger',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enable_disable.job'),
        ),
    ]
